### PR TITLE
Update all dependencies to the latest versions (breaking backwards compatibility)

### PR DESCRIPTION
**Pull request by pcarranzav**
Using https://www.npmjs.com/package/npm-check-updates

The dependencies were already quite old, and I suppose anyone using this module would want the latest chai and sinon - what do you think @jviotti?

I tried it running the tests in https://github.com/resin-io/resin-supervisor/tree/d418a09340c4a9449052c27687264649a3e83e6b/test and they run fine, so dunno how badly broken the backwards compat is.

Change-Type: major
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

### CODE REVIEW

**Comment by pcarranzav** [comment]
I mainly did this because I think `stub.resolves(value)` which was added in sinon 2.0.0 is nice when testing Promise-returning functions.

**Comment by pcarranzav** [comment]
Ugh, looks like this breaks support for older versions of node ( < 4) - though not sure if you wanna maintain support for those now they've hit EOL?

**Comment by jviotti** [comment]
Very nice! 

> Ugh, looks like this breaks support for older versions of node ( < 4) - though not sure if you wanna maintain support for those now they've hit EOL?

Yeah, feel free to increase the bar in this PR :)

**Comment by pcarranzav** [comment]
@jviotti glad you agree! I'm not a collaborator in this repo - would you change the CI tests to only run on node > 4?

**Comment by jviotti** [comment]
@pcarranzav Done! Can you rebase this PR?

**Comment by pcarranzav** [comment]
Done! (Hadn't realized the tests were defined in the repo, sorry, still not very used to how Travis and Appveyor work)

**Comment by jviotti** [comment]
No worries! Thanks a lot!

**Comment by jviotti** [comment]
I published v1.0.1 to npm

**Comment by pcarranzav** [comment]
Thanks @jviotti! (Shouldn't this have been 2.0.0 though?)

**Comment by jviotti** [comment]
Oh, I didn't realize the dependency upgrades would cause a breaking change. I fixed it, and the version is now 2.0.0.

**Pull request merged**
